### ISSUE TITLE
Setting the Retry annotation won't re-apply if a failed apply Job already exists

### ISSUE THREAD

**Issue by cezarsa** [appvia/terranetes-controller#1295]
**Describe the bug**

When I set the annotations `terraform.appvia.io/retry=<now epoch>, terraform.appvia.io/apply: "true"` on a Configuration resource I expected both plan and approval steps Jobs to be created.
However, if there's already a failed Job for the Configuration resource and the Generation did not change only the plan Job is created.

**To Reproduce**

Create a Configuration that fails to apply, set the retry annotation.

**Expected behavior**

I expected both plan and apply Jobs to be created.

**Additional context**

I think the issue comes from the Job list query on the `ensureTerraformApply` not using the retry annotation as label on:
https://github.com/appvia/terranetes-controller/blob/35a734155f34df731a5c0fee625028d72f93ffcf/pkg/controller/configuration/ensure.go#L1205-L1211

The `ensureTerraformPlan` func uses both the Retry and the Drift annotations when filtering Jobs:
https://github.com/appvia/terranetes-controller/blob/35a734155f34df731a5c0fee625028d72f93ffcf/pkg/controller/configuration/ensure.go#L774-L775

Would there be any unforeseen consequences of using that same filter on the apply ensure func?

**Comment by gambol99** [comment]
Apologizes for the delay on this one @cezarsa … I’ve been consumed by other areas at the moment. From the looks of things i suspect you might be right, i can’t think of anything off the top of my head which would cause an issue by adding it ..

**Comment by cezarsa** [comment]
Great, thanks for looking! I'll send a PR for it.

**Comment by gambol99** [comment]
Closing the issue as fixed in #1367
