### ISSUE TITLE
Disabling auto approval causes Configuration to be OutOfSync even with no changes

### ISSUE THREAD

**Issue by cezarsa** [appvia/terranetes-controller#1365]
**Describe the bug**

We've been experimenting with changing our Configurations to have `enableAutoApproval: false` but we've encountered a few issues when trying it.

1. Every time a plan Job is executed, be it by the controller restarting when the old Job no longer exists, or when it's purposely retried, the `TerraformApply` condition is set to `ActionRequired` after the Plan is finished, even when the Plan shows "No changes". This also causes the resource status to be set to `OutOfSync`.

2. Having drift detection enabled makes matters worse, even though the the drift detection ensure func checks the Job output for "No changes" the reconciler still proceeds to the apply ensure func which again sets the condition to `ActionRequired` and the status to `OutOfSync`.

3. If a real drift is detected the apply ensure func will immediately replace the condition set by the drift ensure, also Terranetes won't create a new apply Job even after adding the apply annotation. This is due to the apply condition already being set to true on the current generation and the drift annotation not being used when looking up Apply jobs. (That last part should be fixed by https://github.com/appvia/terranetes-controller/pull/1327)

**To Reproduce**

1. Create a new Configuration with `enableAutoApproval: false`.
2. Add the apply annotation.
3. Wait for apply to finish.
4. Delete the original Plan Job.
5. Restart terranetes-controller pods.

**Expected behavior**

The Configuration was expected to be InSync since no changes to the infra were required. However, Terranetes will show it as OutOfSync requiring approval for running Apply.

**Additional context**

To improve the usability of manually approved Configurations I propose we change Terranetes to only trigger the apply Job if the previous plan showed any diff. This would effectively consist of doing a "drift" check on every reconciliation, right before getting to the apply step.
Currently, this drift check is accomplished by inspecting the output log from the Plan Pod, however, this isn't very reliable as we can't expect the Plan Pod to always exist, especially when doing this check on every reconciliation, a better way of doing it would be inspecting the plan output on the executor pod itself and saving either the full plan or part of it in a Secret. I'm right now experimenting locally with some changes to support this case.

**Comment by gambol99** [comment]
Closing the issue as fixed in #1367
