### ISSUE TITLE
Add limit to the number of Jobs running simultaneously

### ISSUE THREAD

**Issue by cezarsa** [appvia/terranetes-controller#1392]
**Is your feature request related to a problem? Please describe.**

On clusters with a large number (1000+) of Configurations, introducing a change that affects all those Configurations can overload the cluster with thousands of pods created at the same time. This can also cause issues with API rate limiting on whatever provider endpoint is being used.

**Describe the solution you'd like**

I want Terranetes to support a limit of Jobs running simultaneously. The drift controller already has an argument for the number of simultaneous drift checks. What I'm proposing is similar, but it would affect all Configurations regardless of the trigger for the Job creation.

**Describe alternatives you've considered**

One alternative could be controlling the concurrency by introducing changes to existing Configurations in a paced manner, but the agent introducing those changes might not have visibility over the total number of Configurations running on the cluster.

**Comment by gambol99** [comment]
Closing an fixed - the feature https://github.com/appvia/terranetes-controller/pull/1410 will be in the next release
