### ISSUE TITLE
Add ability to customize Job template resources

### ISSUE THREAD

**Issue by Shadowssong** [appvia/terranetes-controller#1499]
**Is your feature request related to a problem? Please describe.**

Hello!  We would like to be able to modify the resources allocated to the Jobs that run our plan/apply jobs, e.g. https://github.com/appvia/terranetes-controller/blob/master/pkg/assets/job.yaml.tpl#L261-L267

In our specific use case, we launch a significant number of jobs on reconcile and due to the extremely low request values for cpu and memory Kubernetes schedules too many pods onto a small number of nodes.  Their usage far exceeds the requests (CPU ranges from 150m to 500m and memory from 150Mi to 500Mi) which ends up overloading the CPU on given nodes.  The jobs do eventually complete, but during that time, any other pods on these nodes are affected by the high CPU usage.

**Describe the solution you'd like**

If possible, it would be great if we could pass cpu and memory requests/limits overrides to the Job template.  I don't quite understand how values are populated into the existing job.yaml.tpl, but something on the chart that follows common resource overrides like

```
templates:
  job:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1024Mi
```

**Describe alternatives you've considered**

We have tested using a custom Job template which overrides the cpu/memory requests to be higher, and this works, but it means that we now have a custom Job template which will need to be manually kept in sync with the upstream version as it evolves over time.  If possible it would be much more desirable to simply expose some of these smaller knobs on the Job via the helm chart.

**Additional context**

Nothing more to add, thank you all for this wonderful project!

**Comment by gambol99** [comment]
Closing the issue as fixed - and should be available in the v0.4.13 which is rolling out now …

**Comment by Shadowssong** [comment]
@gambol99 Thanks so much for that quick turn around, will upgrade and let you know if I run into any issues.  Thanks again!

**Comment by Shadowssong** [comment]
@gambol99 Just a heads up, I think in the release notes for 0.4.13 is pointing to the wrong helm PR, it's pointing to #1494 when it should be pointing to #1502.  No big deal for me just letting you know, thanks again
