### ISSUE TITLE
if ~/.tnctl directory is missing tnctl will not create it

### ISSUE THREAD

**Issue by timstahlappvia** [appvia/terranetes-controller#283]
**Describe the bug**
If you use tnctl to try and scope the search or add certain registries, it will try and write that to ~/.tnctl/config.yaml
If that ~/.tnctl directory does not exist, tnctl will throw an error: 
`[Error]: open /Users/tstahl/.tnctl/config.yaml: no such file or directory`
If you manually create the directory and try again, it will complete successfully.

**To Reproduce**
See above. This is on a system that has not used tnctl to store config in the past. First time using it on my machine.

**Expected behavior**
tnctl should create the config folder if it doesn't exist.

**Screenshots**

**Additional context**

**Comment by gambol99** [comment]
Fixed in PR #284 and will be in the next release
