### ISSUE TITLE
Add any labels specified on the Configuration object to the jobs/pods

### ISSUE THREAD

**Issue by mrsheepuk** [appvia/terranetes-controller#671]
**Is your feature request related to a problem? Please describe.**
We're trying to show the logs of the plan and apply pods, so want to be able to programatically find them using the consistent labels we're applying to the Configuration object.

**Describe the solution you'd like**
All labels specified on the Configuration object copied to the Jobs that implement the plan and apply (and thus pods generated by the job).

**Comment by gambol99** [comment]
Closing as fixed - will be tagging a new release
