### ISSUE TITLE
Cross account provisioning

### ISSUE THREAD

**Issue by samof76** [appvia/terranetes-controller#953]
**Is your feature request related to a problem? Please describe.**
I would want to centrally manage all the terraform configurations, and yet be able to provision resources across accounts.

**Describe the solution you'd like**
It would be nice if we could take AWS(or any cloud) account configuration as an option in the `configuration` kind and operate on that account with the terraform module provided.
 
**Describe alternatives you've considered**
Cross plane does this.

**Additional context**
None

**Comment by gambol99** [comment]
Hi @samof76 

You could configure multiple Provider CRDs, each one with its own credentials and representing a specific account, which a Configuration can reference. Would that not provide the behavior you want?
